language: node_js
services:
  - mysql
node_js:
  - "7"
  - "8"
before_install:
  - mysql -utravis -e 'CREATE DATABASE IF NOT EXISTS teste;'
  - mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'root'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"
  - mysql -e "CREATE TABLE teste.teste (id int(11) NOT NULL AUTO_INCREMENT, nome varchar(45) NOT NULL, idade int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;"
install:
  - "npm install"
