<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../vendor/now-ui-kit/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/now-ui-kit/assets/css/now-ui-kit.css">

    <title>Metric App</title>
</head>
