<!doctype html>
<html lang="pt-br">
<head>
    <style> <?= $this->view->bootstrapCss ?> </style>
    <style> <?= $this->view->nowUiKitCss ?> </style>
    <script src="https://use.fontawesome.com/c3cb34f65e.js"></script>

    <style>
        .ocultar-alerta {
            display: none;
        }
    </style>

</head>
<body>

    <nav class="navbar navbar-expand-lg bg-danger">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="/home">
                    Metrics
                </a>
            </div>

            <div class="collapse navbar-collapse justify-content-end" id="navigation">
                <div class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                        Métricas
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                        <a class="dropdown-item" href="/cadastrar">Cadastrar</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/listar">Métricas Cadastradas</a>
                    </ul>
                </div>
                <div class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                        Tempo
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                        <a class="dropdown-item" href="#">Cadastrar Tempo</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Tempo Cadastrados</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Pomodoro</a>
                    </ul>
                </div>
                <a href="/logout" class="nav-link">
                    logout
                </a>
            </div>
        </div>
    </nav>

    <div class="container">
        <?php if (count($this->view->metricas, COUNT_NORMAL) == 0) { ?>
            <div class="alert alert-warning" role="alert">
                <div class="container">
                    <div class="alert-icon">
                        <i class="fa fa-bell-o"></i>
                    </div>
                    <strong>Não Existe!</strong> Métricas cadastradas para você
                </div>
            </div>
        <?php } else { ?>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Banca</th>
                    <th scope="col">Data da Realização</th>
                    <th scope="col">Quantidade Questões</th>
                    <th scope="col">Quantidade Erros</th>
                    <th scope="col">Quantidade Acertos</th>
                    <th scope="col">Options</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->metricas as $k => $m) {?>
                    <tr>
                        <td><?= $m['banca'] ?></td>
                        <td><?= $m['data_registro'] ?></td>
                        <td><?= $m['quant_questoes'] ?></td>
                        <td><?= $m['quant_error'] ?></td>
                        <td><?= $m['quant_acertos'] ?></td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <button onclick="atualizar(<?= $k ?>)" type="button" class="btn btn-warning">
                                    <span class="fa fa-pencil-square-o"></span>
                                </button>
                                <button onclick="excluir(<?= $m['id']?>)" type="button" class="btn btn-danger">
                                    <span class="fa fa-trash-o"></span>
                                </button>
                            </div>
                        </td>
                    </tr>
                <?php }?>
                </tbody>
            </table>
        <?php } ?>

    </div>


    <script><?= $this->view->jquery ?></script>
    <script><?= $this->view->popper ?></script>
    <script><?= $this->view->bootstrapJs ?></script>
    <script><?= $this->view->nowUiKitJs ?></script>
    <script>
        var atualizar = function (index) {
            console.log(index);
        };

        var excluir = function (id) {
            console.log(id);
        };
    </script>

</body>
</html>
