<!doctype html>
<html lang="pt-br">
<head>
    <style> <?= $this->view->bootstrapCss ?> </style>
    <style> <?= $this->view->nowUiKitCss ?> </style>
    <script src="https://use.fontawesome.com/c3cb34f65e.js"></script>

    <style>
        .ocultar-alerta {
            display: none;
        }

        .cor-font-branca {
            color: white;
        }
    </style>

</head>
<body>

    <nav class="navbar navbar-expand-lg bg-danger">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="/home">
                    Metrics
                </a>
            </div>

            <div class="collapse navbar-collapse justify-content-end" id="navigation">
                <div class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                        Métricas
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                        <a class="dropdown-item" href="/cadastrar">Cadastrar</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/listar">Métricas Cadastradas</a>
                    </ul>
                </div>
                <div class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                        Tempo
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                        <a class="dropdown-item" href="/timer/listar">Tempo Cadastrados</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/pomodoro">Pomodoro</a>
                    </ul>
                </div>
                <a href="/logout" class="nav-link">
                    logout
                </a>
            </div>
        </div>
    </nav>

    <div class="container">
        <?php if (count($this->view->metricas, COUNT_NORMAL) == 0) { ?>
            <div class="alert alert-warning" role="alert">
                <div class="container">
                    <div class="alert-icon">
                        <i class="fa fa-bell-o"></i>
                    </div>
                    <strong>Não Existe!</strong> Métricas cadastradas para você
                </div>
            </div>
        <?php } else { ?>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Banca</th>
                    <th scope="col">Data da Realização</th>
                    <th scope="col">Quantidade Questões</th>
                    <th scope="col">Quantidade Erros</th>
                    <th scope="col">Quantidade Acertos</th>
                    <th scope="col">Options</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->view->metricas as $k => $m) {?>
                    <tr>
                        <td><?= $m['banca'] ?></td>
                        <td><?= $m['data_registro'] ?></td>
                        <td><?= $m['quant_questoes'] ?></td>
                        <td><?= $m['quant_error'] ?></td>
                        <td><?= $m['quant_acertos'] ?></td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <button onclick="atualizar(<?= $m['id'] ?>)" type="button" class="btn btn-warning">
                                    <span class="fa fa-pencil-square-o"></span>
                                </button>
                                <button onclick="modalExcluir(<?= $m['id']?>)" type="button" class="btn btn-danger">
                                    <span class="fa fa-trash-o"></span>
                                </button>
                            </div>
                        </td>
                    </tr>
                <?php }?>
                </tbody>
            </table>
        <?php } ?>

    </div>

    <!-- Modal Core -->
    <div class="modal fade" id="modal-aviso" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content bg-danger">
                <div class="modal-header">
                    <h3 class="modal-title cor-font-branca" id="myModalLabel">Atenção</h3>
                </div>
                <div class="modal-body cor-font-branca">
                    <h4>Você tem certeza que deseja excluir essa métrica ?</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="excluir()">Sim</button>
                    <button type="button" class="btn btn-info" data-dismiss="modal">Não</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Core -->
    <div class="modal fade" id="modal-sucesso" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content bg-success">
                <div class="modal-header">
                    <h3 class="modal-title cor-font-branca" id="myModalLabel">Sucesso</h3>
                </div>
                <div class="modal-body cor-font-branca">
                    <h4>Métrica Excluida com Sucesso</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="modalSucesso()">Ok</button>
                </div>
            </div>
        </div>
    </div>


    <script><?= $this->view->jquery ?></script>
    <script><?= $this->view->popper ?></script>
    <script><?= $this->view->bootstrapJs ?></script>
    <script><?= $this->view->nowUiKitJs ?></script>
    <script>
        var atualizar = function (id) {
            sessionStorage.setItem("idData", id);
            $(location).attr('href', '/atualizar');
        };

        var modalExcluir = function (id) {
            sessionStorage.setItem("idData", id);
            $("#modal-aviso").modal();
        };

        var excluir = function () {
            $.post("/cadastrar/delete", {
                id: sessionStorage.getItem("idData")
            }, function (res, status) {
                if (status === "success") {
                    $("#modal-sucesso").modal();
                }
            });
        };

        var modalSucesso = function () {
          location.reload();
        };
    </script>

</body>
</html>
