<!doctype html>
<html lang="pt-br">
<head>
    <style> <?= $this->view->bootstrapCss ?> </style>
    <style> <?= $this->view->nowUiKitCss ?> </style>

</head>
<body>

<nav class="navbar navbar-expand-lg bg-danger">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="/home">
                Metrics
            </a>
        </div>

        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <div class="dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                    Métricas
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                    <a class="dropdown-item" href="/cadastrar">Cadastrar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/listar">Métricas Cadastradas</a>
                </ul>
            </div>
            <div class="dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                    Tempo
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                    <a class="dropdown-item" href="#">Cadastrar Tempo</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Tempo Cadastrados</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Pomodoro</a>
                </ul>
            </div>
            <a href="/logout" class="nav-link">
                logout
            </a>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                <div class="card-header">Questões <?= date('Y')?></div>
                <div class="card-body">
                    <p>30 Questões</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                <div class="card-header">Tempo <?= date('Y')?></div>
                <div class="card-body">
                    <p>300 minutos</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                <div class="card-header">Aproveitamento <?= date("Y") ?></div>
                <div class="card-body">
                    <p>100%</p>
                </div>
            </div>
        </div>
    </div>
</div>

<canvas id="lineProva" width="200" height="60"></canvas>
<canvas id="barProva" width="200" height="60"></canvas>
<canvas id="lineTempo" width="200" height="60"></canvas>
<canvas id="barTempo" width="200" height="60"></canvas>


<script><?= $this->view->jquery ?></script>
<script><?= $this->view->popper ?></script>
<script><?= $this->view->bootstrapJs ?></script>
<script><?= $this->view->nowUiKitJs ?></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script><?= $this->view->grafJs ?></script>
<script>
    $(document).ready(function () {
       $.post('/home/graphic', function (data, status) {
           var json = JSON.parse(data);

           var data = [10,20,30];
           var lineProva = document.getElementById("lineProva");
           var barProva = document.getElementById("barProva");
           var lineTempo = document.getElementById("lineTempo");
           var barTempo = document.getElementById("barTempo");

           graphicLine(lineProva, [10,20,30]);
           graphicBar(barProva, [10,20,30]);
           graphicLine(lineTempo, [10,20,30]);
           graphicBar(barTempo, [10,20,30]);

       });
    });
</script>
</body>
</html>

