<!doctype html>
<html lang="pt-br">
<head>
    <style> <?= $this->view->bootstrapCss ?> </style>
    <style> <?= $this->view->nowUiKitCss ?> </style>
    <style>
        .infor-questoes {
            text-align: center;
            font-size: 40px;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-expand-lg bg-danger">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="/home">
                Metrics
            </a>
        </div>

        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <div class="dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                    Métricas
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                    <a class="dropdown-item" href="/cadastrar">Cadastrar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/listar">Métricas Cadastradas</a>
                </ul>
            </div>
            <div class="dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                    Tempo
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                    <a class="dropdown-item" href="/timer/listar">Tempo Cadastrados</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/pomodoro">Pomodoro</a>
                </ul>
            </div>
            <a href="/logout" class="nav-link">
                logout
            </a>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                <div class="card-header">Questões <?= date('Y')?></div>
                <div class="card-body">
                    <p id="quant-questoes" class="infor-questoes">0 Questões</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                <div class="card-header">Tempo <?= date('Y')?></div>
                <div class="card-body">
                    <p id="quant-minutos" class="infor-questoes">0 minutos</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                <div class="card-header">Aproveitamento <?= date("Y") ?></div>
                <div class="card-body">
                    <p id="quant-porcent" class="infor-questoes">0%</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card text-white bg-success mb-12" style="max-width: 100%;">
                <div class="card-header">Filtro</div>
                <div class="card-body">
                    <label>Bancas</label>
                    <select id="bancas" class="form-control">
                        <?php foreach ($this->view->bancas as $b) {?>
                            <option value="<?= $b['banca'] ?>"><?= $b['banca'] ?></option>
                        <?php }?>
                    </select>
                    <br>
                    <button class="btn btn-info" onclick="carregar()">Carregar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<canvas id="lineProva" width="200" height="60"></canvas>
<canvas id="barProva" width="200" height="60"></canvas>
<canvas id="lineTempo" width="200" height="60"></canvas>
<canvas id="barTempo" width="200" height="60"></canvas>


<script><?= $this->view->jquery ?></script>
<script><?= $this->view->popper ?></script>
<script><?= $this->view->bootstrapJs ?></script>
<script><?= $this->view->nowUiKitJs ?></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script><?= $this->view->grafJs ?></script>
<script>
    $(document).ready(function () {
       $.post('/home/graphic', function (res, status) {
           var json = JSON.parse(res);


           var lineProva = document.getElementById("lineProva");
           var barProva = document.getElementById("barProva");
           var lineTempo = document.getElementById("lineTempo");
           var barTempo = document.getElementById("barTempo");

           graphicLine(lineProva, json.graf.valores);
           graphicBar(barProva, json.graf.valores);
           graphicLine(lineTempo, json.time.valores);
           graphicBar(barTempo, json.time.valores);

           var totalQuest = json.graf.total_questions;

           var totalMin = json.time.valores.reduce(function (vAnterior, vElem) {
               return vAnterior + vElem;
           }, 0);

           var totalPorcent = (json.graf.total_success / json.graf.total_questions) * 100;

           $("#quant-questoes").text(totalQuest + " Questões");
           $("#quant-minutos").text(totalMin + " Minutos");
           $("#quant-porcent").text(totalPorcent.toFixed(2) + "%");

       });
    });

    var carregar = function() {
        var banca = $("#bancas").val();
        $.post('/home/graphicBanca',{banca: banca}, function (res, status) {
            var json = JSON.parse(res);


            var lineProva = document.getElementById("lineProva");
            var barProva = document.getElementById("barProva");
            var lineTempo = document.getElementById("lineTempo");
            var barTempo = document.getElementById("barTempo");

            graphicLine(lineProva, json.graf.valores);
            graphicBar(barProva, json.graf.valores);
            graphicLine(lineTempo, json.time.valores);
            graphicBar(barTempo, json.time.valores);

            var totalQuest = json.graf.total_questions;

            var totalMin = json.time.valores.reduce(function (vAnterior, vElem) {
                return vAnterior + vElem;
            }, 0);

            var totalPorcent = (json.graf.total_success / json.graf.total_questions) * 100;

            $("#quant-questoes").text(totalQuest + " Questões");
            $("#quant-minutos").text(totalMin + " Minutos");
            $("#quant-porcent").text(totalPorcent.toFixed(2) + "%");

        });
    }
</script>
</body>
</html>

